name: sre_automation
  api_python:
    container_name: api_python
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"

networks:
  sre_api_python_default:
    driver: bridge
    external: true
